dist: trusty
language: php

cache:
  bundler: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

php:
  - 7.1

env:
  - VERSION=HEAD
  # The final CI slot should be used to test the update path from the oldest
  # available database fixture.
  - VERSION=1.2.0-alpha1

matrix:
  fast_finish: true

addons:
  chrome: stable

before_install:
  - phpenv config-add ./tests/travis.php.ini
  - phpenv rehash

  - composer self-update
  - composer --version
  - google-chrome-stable --version

  - export ORCA=$TRAVIS_BUILD_DIR/../orca
  - export ORCA_FIXTURE=$ORCA-build
  - export ORCA_SUT=acquia/headless_lightning
  - export ORCA_PACKAGES_CONFIG=../headless-lightning/tests/packages.yml

  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - export PATH="$ORCA/bin:$PATH"
  - export PATH="$ORCA/vendor/bin:$PATH"
  - export PATH="$ORCA_FIXTURE/vendor/bin:$PATH"

install:
  # Install ORCA so that we can build the fixture using that.
  - git clone --depth 1 --branch lightning https://github.com/acquia/orca.git ../orca
  - "$ORCA/bin/travis/install master"

  # Run ORCA static analysis tools.
  - orca static-analysis:run ./

  # Use ORCA to build the code base.
  - orca fixture:init -f --sut $ORCA_SUT --dev --profile headless_lightning

before_script:
  - cd $ORCA_FIXTURE/docroot
  - $TRAVIS_BUILD_DIR/update.sh $VERSION

script:
  - orca tests:run --sut $ORCA_SUT --sut-only

after_failure:
  - drush watchdog:show --count=100 --severity=Error --extended
