---
language: php

php: "7.3"

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "${TMPDIR:-/tmp}/phpstan/cache"

env:
  global:
    - ORCA_SUT_NAME=acquia/headless_lightning
    - ORCA_SUT_BRANCH=master
    # Specify the version of ORCA to use. Use dev-master to track the latest
    # release, dev-develop to track Dev/HEAD, or any other Composer version
    # string.
    # @see https://getcomposer.org/doc/articles/versions.md
    - ORCA_VERSION=v2.11.5
    - ORCA_PACKAGES_CONFIG_ALTER=../headless_lightning/tests/packages_alter.yml
    - ORCA_FIXTURE_PROFILE=headless_lightning
    - ORCA_FIXTURE_PROJECT_TEMPLATE=acquia/drupal-recommended-project
    - ORCA_TELEMETRY_ENABLE=TRUE

matrix:
  fast_finish: true
  include:
    # Standard ORCA jobs.
    - { name: "Static code analysis", env: ORCA_JOB=STATIC_CODE_ANALYSIS }
    # This job disabled since the SUT's support requirements preclude Drupal 8,
    # when this job was meaningful (i.e., tested for pre-Drupal 9 deprecations,
    # and it is not desirable to test for D9 deprecations at this time.
    # - { name: "Deprecated code scan", env: ORCA_JOB=DEPRECATED_CODE_SCAN_SUT }
    - { name: "Isolated test w/ recommended package versions", env: ORCA_JOB=ISOLATED_RECOMMENDED }
    - { name: "Integrated test w/ recommended package versions", env: ORCA_JOB=INTEGRATED_RECOMMENDED }
    # The previous version of Drupal Core at any time is not currently
    # supported.
    # - { name: "Integrated test w/ recommended package versions & previous minor release of Drupal core", env: ORCA_JOB=CORE_PREVIOUS }
    - { name: "Isolated test w/ dev package versions", env: ORCA_JOB=ISOLATED_DEV }
    - { name: "Integrated test w/ dev package versions", env: ORCA_JOB=INTEGRATED_DEV }
    - { name: "Integrated test w/ dev package versions & next minor dev version of Drupal core", env: ORCA_JOB=CORE_NEXT }
    # Custom job.
    - { name: "Upgrade test", env: ORCA_JOB=CUSTOM ORCA_CUSTOM_FIXTURE_INIT_ARGS="--no-site-install" ORCA_CUSTOM_TESTS_RUN_ARGS="--sut-only" DB_FIXTURE=1.2.0-alpha1 }
  allow_failures:
    - env: ORCA_JOB=ISOLATED_DEV
    - env: ORCA_JOB=INTEGRATED_DEV
    - env: ORCA_JOB=CORE_NEXT

before_install:
  - composer self-update 1.10.16
  - composer create-project --no-dev acquia/orca ../orca "$ORCA_VERSION"
  - ../orca/bin/travis/before_install.sh

install: ./tests/travis/install.sh

before_script: ../orca/bin/travis/before_script.sh

script:
  - ../orca/bin/travis/script.sh

before_cache: ../orca/bin/travis/before_cache.sh

after_success: ../orca/bin/travis/after_success.sh

after_failure: ../orca/bin/travis/after_failure.sh

after_script: ../orca/bin/travis/after_script.sh
